version: 2
updates:
  - package-ecosystem: docker-compose
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
